### ISSUE TITLE
FTrace-Synth

### ISSUE THREAD

**Issue by andrewilyas** [ekinakyurek/influence#5]
Hi, thanks for your really interesting work! I wanted to explore the Ftrace-Synth dataset but it seems like only the TRex-based variant is available on hugging face. Is there any way to get access to Ftrace-Synth, ideally through a similar API?

**Comment by ekinakyurek** [comment]
Hi @andrewilyas,

I added synthetic data files as LFS under this folder https://github.com/ekinakyurek/influence/tree/synthetic/Synth/synth_data_synth_07_27

The `test` one is the query set, the `train` one is the attribution corpus.

Let me know if you can download them?

Each line in these files is a data point:

```JSON
{"inputs_pretokenized": "<extra_id_0> is a member of MMMMDCCLXXXIV-entity", "targets_pretokenized": "<extra_id_0> entity-MIV", "uuid": "r30-e1004-e4784-rx0-ex2-ex3-s0", "proponents": ["r30-e1004-e4784-rx1-ex3-ex0-s0", "r30-e1004-e4784-rx1-ex3-ex0-s1", "r30-e1004-e4784-rx0-ex1-ex2-s0", "r30-e1004-e4784-rx0-ex1-ex2-s1", "r30-e1004-e4784-rx1-ex3-ex1-s0", "r30-e1004-e4784-rx1-ex3-ex1-s1", "r30-e1004-e4784-rx0-ex1-ex1-s0", "r30-e1004-e4784-rx0-ex1-ex1-s1", "r30-e1004-e4784-rx1-ex2-ex0-s0", "r30-e1004-e4784-rx1-ex2-ex0-s1", "r30-e1004-e4784-rx0-ex2-ex2-s0", "r30-e1004-e4784-rx0-ex2-ex2-s1", "r30-e1004-e4784-rx1-ex1-ex0-s0", "r30-e1004-e4784-rx1-ex1-ex0-s1", "r30-e1004-e4784-rx0-ex0-ex1-s0", "r30-e1004-e4784-rx0-ex0-ex1-s1", "r30-e1004-e4784-rx0-ex1-ex0-s0", "r30-e1004-e4784-rx0-ex1-ex0-s1", "r30-e1004-e4784-rx1-ex3-ex2-s0", "r30-e1004-e4784-rx1-ex3-ex2-s1", "r30-e1004-e4784-rx0-ex0-ex0-s0", "r30-e1004-e4784-rx0-ex0-ex0-s1", "r30-e1004-e4784-rx1-ex0-ex1-s0", "r30-e1004-e4784-rx1-ex0-ex1-s1", "r30-e1004-e4784-rx1-ex0-ex0-s0", "r30-e1004-e4784-rx1-ex0-ex0-s1", "r30-e1004-e4784-rx1-ex1-ex1-s0", "r30-e1004-e4784-rx1-ex1-ex1-s1", "r30-e1004-e4784-rx1-ex3-ex3-s0", "r30-e1004-e4784-rx1-ex3-ex3-s1", "r30-e1004-e4784-rx0-ex3-ex3-s0", "r30-e1004-e4784-rx0-ex3-ex3-s1", "r30-e1004-e4784-rx0-ex0-ex3-s0", "r30-e1004-e4784-rx0-ex0-ex3-s1", "r30-e1004-e4784-rx0-ex2-ex0-s0", "r30-e1004-e4784-rx0-ex2-ex0-s1", "r30-e1004-e4784-rx1-ex2-ex2-s0", "r30-e1004-e4784-rx1-ex2-ex2-s1", "r30-e1004-e4784-rx0-ex2-ex1-s0", "r30-e1004-e4784-rx0-ex2-ex1-s1", "r30-e1004-e4784-rx1-ex1-ex2-s0", "r30-e1004-e4784-rx1-ex1-ex2-s1", "r30-e1004-e4784-rx1-ex1-ex3-s0", "r30-e1004-e4784-rx1-ex1-ex3-s1", "r30-e1004-e4784-rx1-ex0-ex2-s0", "r30-e1004-e4784-rx1-ex0-ex2-s1", "r30-e1004-e4784-rx0-ex1-ex3-s0", "r30-e1004-e4784-rx0-ex1-ex3-s1", "r30-e1004-e4784-rx1-ex2-ex3-s0", "r30-e1004-e4784-rx1-ex2-ex3-s1", "r30-e1004-e4784-rx1-ex0-ex3-s0", "r30-e1004-e4784-rx1-ex0-ex3-s1", "r30-e1004-e4784-rx0-ex3-ex0-s0", "r30-e1004-e4784-rx0-ex3-ex0-s1", "r30-e1004-e4784-rx0-ex3-ex2-s0", "r30-e1004-e4784-rx0-ex3-ex2-s1", "r30-e1004-e4784-rx0-ex3-ex1-s0", "r30-e1004-e4784-rx0-ex3-ex1-s1", "r30-e1004-e4784-rx0-ex0-ex2-s0", "r30-e1004-e4784-rx0-ex0-ex2-s1", "r30-e1004-e4784-rx1-ex2-ex1-s0", "r30-e1004-e4784-rx1-ex2-ex1-s1"]}
```
    
The fields `inputs_pretokenized` and `targets_pretokenized` are inputs and ouputs to as before. The "proponents" tells the ids (corresponds to `uuid` field) of supporting examples in the training set.  You can use proponents field to match facts.

(you can see this [file](https://github.com/ekinakyurek/influence/blob/synthetic/eval/evaluate.py) to see how I use these fields to evaluate bm25 algorithm)

**Extra information**

The `uuid` is unique identifier for an example: `"uuid": "r30-e1004-e4784-rx0-ex2-ex3-s0"`.  

- 1st field tells the relation id: "r30" -> relation 30.  
- 2nd field is the first entity's id: "e1004" -> entity 1004.  
- 3rd field is the second entity's id: "e4784" -> entity 4783.  
- 4th field is the surface form of the relation: "rx0" -> 0th surface form of relation 30.  
- 5th field is the surface form of the first entity: "ex2" -> "2nd surface form of entity 1004".  
- 6th field is the surface form of the first entity: "ex3" -> "3rd surface form of entity 4783".  
- 7th field specifies which entity is maked: "s0" -> "first entity is masked".  

Please let me know if you have any questions?

**Comment by andrewilyas** [comment]
Thanks for the quick reply, I'll try this out and let you know if I run into trouble!

**Comment by andrewilyas** [comment]
Hi @ekinakyurek,

When downloading the file I get the following error:
```
{
  "message": "This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.",
  "documentation_url": "https://docs.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/"
}
```
We can maybe do it over dropbox instead? Alternatively I noticed we are both at MIT, so I can copy it if it's somewhere accessible (like AFS)?

**Comment by ekinakyurek** [comment]
I am sorry for that. I bought a data plan on GitHub after your message. It should be downloadable right now. Can you try again?

**Comment by andrewilyas** [comment]
Thanks!!
